# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  app.product.repository:
    class: MyApp\Bundle\ProductBundle\Product\Repository\MySqlProductRepository
    public: false
    arguments:
        - "@doctrine.orm.default_entity_manager"

  app.product.command_handler.create:
    class: MyApp\Component\Product\Application\CommandHandler\Product\CreateProductHandler
    public: true
    arguments:
        - '@app.product.repository'

  app.product.command_handler.update:
    class: MyApp\Component\Product\Application\CommandHandler\Product\UpdateProductHandler
    public: true
    arguments:
        - '@app.product.repository'

  app.product.command_handler.delete:
    class: MyApp\Component\Product\Application\CommandHandler\Product\DeleteProductHandler
    public: true
    arguments:
        - '@app.product.repository'

  app.product.command_handler.read_all:
      class: MyApp\Component\Product\Application\CommandHandler\Product\ReadProductAllHandler
      public: true
      arguments:
        - '@app.product.repository'
  
  app.product.command_handler.read_byid:
      class: MyApp\Component\Product\Application\CommandHandler\Product\ReadProductByIdHandler
      public: true
      arguments:
        - '@app.product.repository'

  app.owner.repository:
    class: MyApp\Bundle\ProductBundle\Owner\Repository\MySqlOwnerRepository
    public: false
    arguments:
        - "@doctrine.orm.default_entity_manager"

  app.owner.command_handler.create:
    class: MyApp\Component\Product\Application\CommandHandler\Owner\CreateOwnerHandler
    public: true
    arguments:
        - '@app.owner.repository'

  app.owner.command_handler.read_all:
      class: MyApp\Component\Product\Application\CommandHandler\Owner\ReadOwnerAllHandler
      public: true
      arguments:
        - '@app.owner.repository'