# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  app.owner.repository:
    class: MyApp\Bundle\ProductBundle\Owner\Repository\MySqlOwnerRepository
    public: false
    arguments:
        - "@doctrine.orm.default_entity_manager"

  app.owner.command_handler.create:
    class: MyApp\Component\Product\Application\CommandHandler\Owner\CreateOwnerHandler
    public: true
    arguments:
        - '@app.owner.repository'

  app.owner.command_handler.read_all:
      class: MyApp\Component\Product\Application\CommandHandler\Owner\ReadOwnerAllHandler
      public: true
      arguments:
        - '@app.owner.repository'