MyApp\Component\Product\Domain\Owner:
  type: entity
  table: owner
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      length: 100
